
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from "./config.js";
const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const app=document.getElementById("app");
let user=JSON.parse(localStorage.getItem("agna_user")||"null");
let page="dashboard";
const REQ=8.5,LUNCH=1;
const today=()=>new Date().toISOString().slice(0,10);
const now=()=>new Date().toISOString();
const tf=x=>x?new Date(x).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}):"-";
const h=(a,b)=>(new Date(b)-new Date(a))/36e5;
const r=n=>Math.round((Number(n)||0)*100)/100;
function msg(t,m){let e=document.getElementById("msg");if(e)e.innerHTML=`<div class="msg ${t}">${m}</div>`}
async function login(){
 const id=document.getElementById("employee_id").value.trim(), pw=document.getElementById("password").value.trim();
 const {data,error}=await supabase.from("employees").select("*").eq("employee_id",id).eq("password",pw).eq("active",true).maybeSingle();
 if(error||!data){msg("err","Invalid Employee ID or password.");return}
 user=data;localStorage.setItem("agna_user",JSON.stringify(user));page="dashboard";render();
}
function logout(){localStorage.removeItem("agna_user");user=null;render()}
function loginHTML(){return `<div class="login"><div class="box"><div class="center"><div class="logo">A</div><h2>Agna 3D Designs Pvt Ltd</h2><p class="muted">Attendance & Daily Work Report</p></div><div id="msg"></div><div class="field"><label>Employee ID</label><input id="employee_id" placeholder="ADMIN001 / AG001"></div><div class="field"><label>Password</label><input id="password" type="password"></div><button class="btn" style="width:100%" onclick="login()">Sign In</button><p class="muted">Admin creates employee accounts and passwords.</p></div></div>`}
function nb(p,l){return `<button class="${page==p?'on':''}" onclick="go('${p}')">${l}</button>`}
function title(){return {dashboard:"Dashboard",attendance:"My Attendance",daily:"Daily Report",employees:"Employee Management",allAttendance:"Attendance Reports",allReports:"Daily Reports",monthly:"Monthly Summary"}[page]||"Dashboard"}
function shell(){let admin=user.role==="admin";return `<div class="layout"><aside class="side"><div class="brand"><div class="logo">A</div><h3>Agna 3D<br>Designs Pvt Ltd</h3></div><div class="nav">${nb("dashboard","Dashboard")}<div class="navtitle">Employee</div>${nb("attendance","My Attendance")}${nb("daily","Daily Report")}${admin?`<div class="navtitle">Admin</div>${nb("employees","Employees")}${nb("allAttendance","Attendance Reports")}${nb("allReports","Daily Reports")}${nb("monthly","Monthly Summary")}`:""}</div><button class="btn alt spacer" onclick="logout()">Logout</button></aside><main><div class="top"><div><h2>${title()}</h2><div class="muted">${user.full_name||user.name||user.employee_id} · ${user.role}</div></div><button class="btn alt" onclick="logout()">Logout</button></div><div id="content" class="content"></div></main></div>`}
window.go=p=>{page=p;content()}
async function dashboard(){
 let admin=user.role==="admin",emp=1,present=0,repc=0,prod=0;
 if(admin){
  const e=await supabase.from("employees").select("*").eq("active",true);emp=e.data?.length||0;
  const a=await supabase.from("attendance").select("*").eq("attendance_date",today());present=a.data?.filter(x=>x.check_in).length||0;
  const rr=await supabase.from("daily_reports").select("*").eq("report_date",today());repc=rr.data?.length||0;prod=repc?rr.data.reduce((s,x)=>s+Number(x.productivity_percent||0),0)/repc:0;
 }else{
  const a=await supabase.from("attendance").select("*").eq("employee_id",user.employee_id).eq("attendance_date",today());present=a.data?.filter(x=>x.check_in).length||0;
  const rr=await supabase.from("daily_reports").select("*").eq("employee_id",user.employee_id).eq("report_date",today());repc=rr.data?.length||0;prod=repc?rr.data.reduce((s,x)=>s+Number(x.productivity_percent||0),0)/repc:0;
 }
 return `<div class="cards"><div class="card"><div class="muted">Employees</div><div class="val">${emp}</div></div><div class="card"><div class="muted">Present Today</div><div class="val">${present}</div></div><div class="card"><div class="muted">Reports Today</div><div class="val">${repc}</div></div><div class="card"><div class="muted">Avg Productivity</div><div class="val">${r(prod)}%</div></div></div><div class="grid"><div class="card"><h3>Attendance Rule</h3><p>Office Time: <b>9:00 AM to 6:30 PM</b></p><p>Lunch Break: <b>1 hour auto deduction</b></p><p>Expected Work Time: <b>8.5 hours</b></p></div><div class="card"><h3>Productivity Rule</h3><p>Multiple projects per day supported.</p><p><b>Productivity % = Completed / Target × 100</b></p></div></div>`
}
async function att(){
 const {data}=await supabase.from("attendance").select("*").eq("employee_id",user.employee_id).eq("attendance_date",today()).maybeSingle();
 return `<div class="card"><h3>Today Attendance</h3><p>Date: <b>${today()}</b></p><p>Check In: <b>${tf(data?.check_in)}</b></p><p>Check Out: <b>${tf(data?.check_out)}</b></p><p>Actual Working Hours: <b>${data?.actual_working_hours||0}</b></p><p>Status: <b>${data?.attendance_status||"Not Started"}</b></p><div class="actions"><button class="btn" onclick="checkIn()">Check In</button><button class="btn alt" onclick="checkOut()">Check Out</button></div><p class="muted">1 hour lunch break will be deducted automatically at check out.</p></div>`
}
window.checkIn=async()=>{const ex=await supabase.from("attendance").select("*").eq("employee_id",user.employee_id).eq("attendance_date",today()).maybeSingle();if(ex.data?.check_in){alert("Already checked in.");return}const {error}=await supabase.from("attendance").insert({employee_id:user.employee_id,attendance_date:today(),check_in:now(),attendance_status:"Working",status:"Present"});if(error)alert(error.message);else content()}
window.checkOut=async()=>{const res=await supabase.from("attendance").select("*").eq("employee_id",user.employee_id).eq("attendance_date",today()).maybeSingle();let d=res.data;if(!d?.check_in){alert("Please check in first.");return}if(d.check_out){alert("Already checked out.");return}let out=now(),total=h(d.check_in,out),actual=Math.max(0,total-LUNCH),min=Math.round((actual-REQ)*60),st=min>=0?"Completed":"Short";const {error}=await supabase.from("attendance").update({check_out:out,total_hours:r(total),lunch_break_hours:LUNCH,actual_working_hours:r(actual),required_hours:REQ,short_or_extra_minutes:min,attendance_status:st}).eq("id",d.id);if(error)alert(error.message);else content()}
function form(){return `<div class="card"><h3>Submit Daily Work Report</h3><div id="msg"></div><div class="formgrid"><div class="field"><label>Date</label><input id="report_date" type="date" value="${today()}"></div><div class="field"><label>Project Name</label><input id="project_name"></div><div class="field"><label>Task Name</label><input id="task_name"></div><div class="field"><label>Target</label><input id="target_qty" type="number"></div><div class="field"><label>Completed</label><input id="completed_qty" type="number"></div><div class="field full"><label>Work Description</label><textarea id="work_description"></textarea></div><div class="field full"><label>Remarks</label><textarea id="remarks"></textarea></div></div><button class="btn" onclick="submitReport()">Submit</button><p class="muted">For two projects in one day, submit two separate reports.</p></div><div class="card" style="margin-top:14px"><h3>My Recent Reports</h3><div id="myReports"></div></div>`}
window.submitReport=async()=>{let t=Number(target_qty.value||0),c=Number(completed_qty.value||0),p=t?c/t*100:0;let row={employee_id:user.employee_id,report_date:report_date.value,project_name:project_name.value,task_name:task_name.value,target_qty:t,completed_qty:c,productivity_percent:r(p),work_description:work_description.value,remarks:remarks.value};const {error}=await supabase.from("daily_reports").insert(row);if(error)msg("err",error.message);else{msg("ok","Report submitted.");content()}}
async function myReports(){let el=document.getElementById("myReports");if(!el)return;let {data}=await supabase.from("daily_reports").select("*").eq("employee_id",user.employee_id).order("created_at",{ascending:false}).limit(20);el.innerHTML=reportTable(data||[])}
function reportTable(rows){return `<div class="table"><table><tr><th>Date</th><th>Employee</th><th>Project</th><th>Task</th><th>Target</th><th>Completed</th><th>%</th><th>Remarks</th></tr>${rows.map(x=>`<tr><td>${x.report_date||""}</td><td>${x.employee_id}</td><td>${x.project_name||""}</td><td>${x.task_name||""}</td><td>${x.target_qty||0}</td><td>${x.completed_qty||0}</td><td>${x.productivity_percent||0}%</td><td>${x.remarks||""}</td></tr>`).join("")||`<tr><td colspan="8">No records</td></tr>`}</table></div>`}
function attTable(rows){return `<div class="table"><table><tr><th>Date</th><th>Employee</th><th>In</th><th>Out</th><th>Total</th><th>Lunch</th><th>Actual</th><th>Short/Extra Min</th><th>Status</th></tr>${rows.map(x=>`<tr><td>${x.attendance_date}</td><td>${x.employee_id}</td><td>${tf(x.check_in)}</td><td>${tf(x.check_out)}</td><td>${x.total_hours||0}</td><td>${x.lunch_break_hours||1}</td><td>${x.actual_working_hours||0}</td><td>${x.short_or_extra_minutes||0}</td><td>${x.attendance_status||""}</td></tr>`).join("")||`<tr><td colspan="9">No records</td></tr>`}</table></div>`}
async function employees(){
 const {data}=await supabase.from("employees").select("*").order("created_at",{ascending:false});
 return `<div class="card"><h3>Add Employee</h3><div id="msg"></div><div class="formgrid"><div class="field"><label>Employee ID</label><input id="e_id"></div><div class="field"><label>Full Name</label><input id="e_name"></div><div class="field"><label>Email</label><input id="e_email"></div><div class="field"><label>Password</label><input id="e_pw" value="123456"></div><div class="field"><label>Department</label><input id="e_dep"></div><div class="field"><label>Designation</label><input id="e_des"></div><div class="field"><label>Role</label><select id="e_role"><option>employee</option><option>admin</option></select></div></div><button class="btn" onclick="addEmp()">Add Employee</button></div><div class="card" style="margin-top:14px"><h3>Employees</h3><div class="table"><table><tr><th>ID</th><th>Name</th><th>Email</th><th>Dept</th><th>Designation</th><th>Role</th><th>Active</th><th>Action</th></tr>${(data||[]).map(e=>`<tr><td>${e.employee_id}</td><td>${e.full_name||e.name||""}</td><td>${e.email||""}</td><td>${e.department||""}</td><td>${e.designation||""}</td><td>${e.role||"employee"}</td><td>${e.active!==false?"Yes":"No"}</td><td><button class="btn red" onclick="removeEmp('${e.employee_id}')">Remove</button></td></tr>`).join("")}</table></div></div>`
}
window.addEmp=async()=>{let row={employee_id:e_id.value,full_name:e_name.value,email:e_email.value,password:e_pw.value,department:e_dep.value,designation:e_des.value,role:e_role.value,active:true};const {error}=await supabase.from("employees").insert(row);if(error)msg("err",error.message);else content()}
window.removeEmp=async(id)=>{if(!confirm("Deactivate employee?"))return;const {error}=await supabase.from("employees").update({active:false}).eq("employee_id",id);if(error)alert(error.message);else content()}
async function allAtt(){let {data}=await supabase.from("attendance").select("*").order("attendance_date",{ascending:false}).limit(300);return `<div class="card"><h3>Attendance Reports</h3>${attTable(data||[])}</div>`}
async function allRep(){let {data}=await supabase.from("daily_reports").select("*").order("report_date",{ascending:false}).limit(500);return `<div class="card"><h3>Daily Work Reports</h3>${reportTable(data||[])}</div>`}
async function monthly(){let {data}=await supabase.from("daily_reports").select("*").limit(1000);let s={};(data||[]).forEach(x=>{s[x.employee_id]??={t:0,c:0};s[x.employee_id].t+=Number(x.target_qty||0);s[x.employee_id].c+=Number(x.completed_qty||0)});let rows=Object.entries(s).map(([id,v])=>`<tr><td>${id}</td><td>${v.t}</td><td>${v.c}</td><td>${v.t?r(v.c/v.t*100):0}%</td></tr>`).join("");return `<div class="card"><h3>Monthly Productivity Summary</h3><table><tr><th>Employee</th><th>Total Target</th><th>Total Completed</th><th>Productivity</th></tr>${rows||`<tr><td colspan="4">No records</td></tr>`}</table></div>`}
async function content(){if(!user){render();return}app.innerHTML=shell();let c=document.getElementById("content");if(page==="dashboard")c.innerHTML=await dashboard();if(page==="attendance")c.innerHTML=await att();if(page==="daily"){c.innerHTML=form();await myReports()}if(page==="employees")c.innerHTML=await employees();if(page==="allAttendance")c.innerHTML=await allAtt();if(page==="allReports")c.innerHTML=await allRep();if(page==="monthly")c.innerHTML=await monthly()}
function render(){if(!user)app.innerHTML=loginHTML();else content()}
window.login=login;window.logout=logout;render();
